#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then use that shell instead.
#
#   (2) Put the JDK directory in your environment variable JAVA_HOME before running this script.
#
##############################################################################

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn() {
    if [ "$QUIET" != yes ]; then
        echo "$@"
    fi
}

die() {
    echo
    echo "$@"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

SCRIPT="$0"

# Make the script absolute.
cd "$(dirname "$SCRIPT")" || exit
SCRIPT="$(pwd -P)/$(basename "$SCRIPT")"

# Sed to change a Windows-style path to a Unix-style path.
WINDIR_SED_EXPR='s|\\\\\\\\|/|g'

# Sed to change a Unix-style path to a Windows-style path.
UNIXDIR_SED_EXPR='s|/|\\\\\\\\|g'

while [ -h "$SCRIPT" ] ; do
    ls=$(ls -ld "$SCRIPT")
    link=$(expr "$ls" : '.*-> \(.*\)$')
    if expr "$link" : '/.*' > /dev/null; then
        SCRIPT="$link"
    else
        SCRIPT="$(dirname "$SCRIPT")/$link"
    fi
done

# Starting from N, the use of unset was removed (along with other validations).
# However, the prefix of choice for them, 'GRADLE_SKIP', might have been in use
# and shadowing this function. So to keep backward compatibility, use GRADLE_SKIP.
if [ "${GRADLE_SKIP_VALIDATION:-}" != "true" ] ; then

    classpath="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

    if [ ! -f "$classpath" ] ; then
        die "Gradle wrapper not found in $(dirname "$APP_HOME")/gradle/wrapper"
    fi
fi

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $( ulimit -n ) in #(
      ( *unlimited* | *2147483647* ) :
        ;;
      #(
      ( * ) :
        ulimit -n 262144
        ;;
    esac
fi

# Escape application args
for arg do
    if $darwin; then
        case $arg in #(
        -XstartOnFirstThread) shift ;;
        -D*) shift ;;
        -W*) shift ;;
        esac
    fi
    printf '%s\n' "$arg" | sed "$UNIXDIR_SED_EXPR"
done | xargs -0 "$JAVACMD" \
        -Dorg.gradle.appname="$APP_BASE_NAME" \
        -Dorg.gradle.wrapper.properties="$APP_HOME/gradle/wrapper/gradle-wrapper.properties" \
        -classpath "$classpath" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"
